[[headers]]
for = "/*.json"

[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "application/json"

[[headers]]
for = "/prompts/*.json"

[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "application/json"

[build]
publish = "dist"
command = "npm run build"